[tools]
golang = '1.17.6'
python = '3.11.6'
task = '3.31.0'
vault = '1.15.2'
terraform = '1.6.5'
kubectl = '1.27.2'
nodejs = '18.15.0'
fzf = '0.44.0'
yq = '4.40.1'
jq = '1.7'
gomplate = 'v3.11.6'
teller = '1.5.6'
sops = '3.8.1'
vendir = '0.38.0'
