# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
silent: true

tasks:
  show:
    desc: Show variables for dotnet core tasks
    cmds:
      - |
        echo "ED_SERVER: {{.ED_SERVER}}"

  install:ldap:packages:
    desc: Install ldap package library dlls for powershell core
    cmds:
      - |
        dotnet new console
        dotnet add package Microsoft.Extensions.Logging.Abstractions
        dotnet add package Novell.Directory.Ldap.NETStandard
