# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
silent: true
tasks:
  show:
    desc: Show kube variables
    cmds:
      - |
        echo "local_bin_path: {{.local_bin_path}}"

  install:
    desc: Install steampipe
    cmds:
      - |
        if [ "$OS" = "Windows_NT" ]; then
          echo "Error: Windows is not supported yet." 1>&2
          exit 1
        else
          case $(uname -sm) in
          "Darwin x86_64") target="darwin_amd64.zip" ;;
          "Darwin arm64") target="darwin_arm64.zip" ;;
          "Linux x86_64") target="linux_amd64.tar.gz" ;;
          "Linux aarch64") target="linux_arm64.tar.gz" ;;
          *) echo "Error: '$(uname -sm)' is not supported yet." 1>&2;exit 1 ;;
          esac
        fi
        steampipe_uri="https://github.com/turbot/steampipe/releases/latest/download/steampipe_${target}"
        exe="{{.local_bin_path}}/steampipe"

        tmp_dir="$(mktemp -d)"
        tmp_dir="${tmp_dir%/}"
        echo "Created temporary directory at $tmp_dir. Changing to $tmp_dir"
        cd "$tmp_dir"
        case $(uname -s) in
          "Darwin") zip_location="$tmp_dir/steampipe.zip" ;;
          "Linux") zip_location="$tmp_dir/steampipe.tar.gz" ;;
          *) echo "Error: steampipe is not supported on '$(uname -s)' yet." 1>&2;exit 1 ;;
        esac
        if ! curl --fail --location --progress-bar --output "$zip_location" "$steampipe_uri"; then
          echo "Could not find version of steampipe!"
          exit 1
        fi

        echo "Deflating downloaded archive"
        tar -xf "$zip_location" -C "$tmp_dir"

        echo "Installing"
        mkdir -p "{{.local_bin_path}}"
        mv "$tmp_dir/steampipe" "{{.local_bin_path}}"

        echo "Applying necessary permissions"
        chmod +x $exe

        echo "Removing downloaded archive"
        rm "$zip_location"

        echo "Steampipe was installed successfully to $exe"
    status:
      - test -f {{.local_bin_path}}/steampipe

  install:plugins:
    desc: Install steampipe plugins
    deps:
      - install
    cmds:
      - |
        {{.local_bin_path}}/steampipe plugin install theapsgroup/vault
        {{.local_bin_path}}/steampipe plugin install rss
        {{.local_bin_path}}/steampipe plugin install aws
        {{.local_bin_path}}/steampipe plugin install theapsgroup/gitlab
