# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  all:
    - task: markdown
    - task: yaml
    - task: format

  markdown:
    desc: Lint Markdown
    cmds:
      - markdownlint -c '.github/linters/.markdownlint.yaml' *.md **/*.md

  yaml:
    desc: Lint YAML
    cmds:
      - yamllint {{.BASE_DIR}}

  format:
    desc: Lint general formatting
    cmds:
      - prettier --ignore-path '.github/linters/.prettierignore' --check .
