# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
silent: true
vars:
  aiac_path: "{{.LOCAL_BIN_PATH}}/aiac"
  OPENAI_API_KEY:
    sh: 'echo ${OPENAI_API_KEY:-""}'

tasks:
  show:
    desc: "Show variables"
    cmds:
      - |
        echo "aiac_path: {{.aiac_path}}"
        echo "ROOT_PATH: {{.ROOT_DIR}}"
        echo "LOCAL_BIN_PATH: {{.LOCAL_BIN_PATH}}"
        echo "OPENAI_API_KEY: {{.OPENAI_API_KEY}}"

  install:
    desc: Install aiac
    cmds:
      #- mkdir -p "{{.LOCAL_BIN_PATH}}"
      - cd /tmp
      - wget https://github.com/gofireflyio/aiac/releases/download/v1.0.0/aiac_1.0.0_Linux-64bit.tar.gz
      - tar -zxvf ./aiac_1.0.0_Linux-64bit.tar.gz
      - cp aiac {{.aiac_path}}
    status:
      - test -f {{.aiac_path}}
