# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"
tasks:
  show:
    desc: Show variables for this task
    cmds:
      - |
        echo "GIT_LATEST_TAG: {{.GIT_LATEST_TAG}}"
        echo "VERSION: {{.VERSION}}"
        echo "local_bin_path: {{.local_bin_path}}"

  run:
    desc: Run vault, persist the database locally
    vars:
      VAULT_CONFIG: '{{ .VAULT_CONFIG | default "./config/vault.hcl" }}'

    cmds:
      - vault server -config={{.VAULT_CONFIG}}

  keybase:init:
    desc: Initialize vault with keybase pgp key
    vars:
      KEYBASE_USER: ""
    env:
      VAULT_ADDR: http://127.0.0.2:8200
    cmds:
      - vault operator init -key-shares=1 -key-threshold=1 -pgp-keys="keybase:zloeber"

  install:
    desc: Install vault binary
    cmds:
      - |
        mkdir -p {{.local_bin_path}}
        _suffix="+ent"
        _platform={{OS}}
        _arch={{ARCH}}
        _version=1.12.1
        _vendorapp=vault
        mkdir -p /tmp/${_vendorapp}
        curl --retry 3 --retry-delay 5 --fail -sSL -o /tmp/${_vendorapp}/${_vendorapp}.zip \
          https://releases.hashicorp.com/${_vendorapp}/${_version}${_suffix}/${_vendorapp}_${_version}${_suffix}_${_platform}_${_arch}.zip

        unzip -d /tmp/${_vendorapp} /tmp/${_vendorapp}/${_vendorapp}.zip
        mv /tmp/${_vendorapp}/${_vendorapp} {{.local_bin_path}}
        rm -rf /tmp/${_vendorapp}
        chmod +x {{.local_bin_path}}/${_vendorapp}
        echo "Vault binary installed: {{.local_bin_path}}/${_vendorapp}"
    status:
      - test -f {{.local_bin_path}}/vault

  hsm:softhsm:init:
    desc: Initialize the local softHSM for vault
    vars:
      TARGET_PATH: "~/.config/sops/age"
      TARGET_FILE: "{{.TARGET_PATH}}/keys.txt"
      TEMP_FILE:
        sh: mktemp -u
    cmds:
      - |
        echo "Initializing SoftHSM to be able to create a working example (only for dev),"
        echo "sharing the HSM device is emulated with a pre-created keypair in the image."
        #brew install softhsm
        echo "HSM_PIN: ${HSM_PIN}"
        softhsm2-util --init-token --free --label bank-vaults --so-pin banzai --pin banzai
        #pkcs11-tool --module /usr/local/lib/softhsm/libsofthsm2.so --keypairgen --key-type rsa:2048 --pin "${HSM_PIN}" --token-label bank-vaults --label bank-vaults
