---
name: Lint

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  Lint:
    name: Yamllint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
      - name: Run yamllint
        run: yamllint
